export type Product = {
  slug: string; name: string; category: "Tops" | "Shorts" | "Trousers" | "Sauna" | "Supplements";
  price: number; image: string; badge?: string; sizes: string[]; activity: string; fit: string; feature: string;
  description: string; details: string[];
};

export const products: Product[] = [
  { slug:"apex-compression-tee", name:"Apex Compression Tee", category:"Tops", price:8490, badge:"Best seller", sizes:["S","M","L","XL"], activity:"Lifting", fit:"Compression", feature:"Sweat wicking", image:"https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=1000&q=85", description:"Second-skin training layer engineered for unrestricted heavy sessions.", details:["Four-way stretch jersey","Flatlock seams","Quick-dry finish","Machine wash cold"] },
  { slug:"oversized-training-tee", name:"Oversized Training Tee", category:"Tops", price:6990, badge:"New", sizes:["S","M","L","XL","XXL"], activity:"Everyday", fit:"Oversized", feature:"Breathable", image:"https://images.unsplash.com/photo-1584380931214-dbb5b72e7fd0?auto=format&fit=crop&w=1000&q=85", description:"Heavy-feel cotton blend with room through the chest and shoulders.", details:["240gsm cotton blend","Dropped shoulder","Relaxed hem","Machine wash cold"] },
  { slug:"velocity-5-short", name:"Velocity 5\" Training Short", category:"Shorts", price:6990, badge:"Core", sizes:["S","M","L","XL"], activity:"Conditioning", fit:"Regular", feature:"Zip pockets", image:"https://images.unsplash.com/photo-1538805060514-97d9cc17730c?auto=format&fit=crop&w=1000&q=85", description:"Lightweight training short built to move through circuits and sprints.", details:["5-inch inseam","Secure zip pockets","Elastic drawcord waist","Fast-drying shell"] },
  { slug:"forge-7-short", name:"Forge 7\" Lifting Short", category:"Shorts", price:7490, sizes:["S","M","L","XL","XXL"], activity:"Lifting", fit:"Athletic", feature:"Four-way stretch", image:"https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=1000&q=85", description:"Stable through the waist with enough stretch for deep-range training.", details:["7-inch inseam","Gusset construction","Phone pocket","Abrasion-resistant weave"] },
  { slug:"rest-day-jogger", name:"Rest Day Tapered Jogger", category:"Trousers", price:9990, badge:"Editor pick", sizes:["S","M","L","XL"], activity:"Everyday", fit:"Tapered", feature:"Soft touch", image:"https://images.unsplash.com/photo-1552902865-b72c031ac5ea?auto=format&fit=crop&w=1000&q=85", description:"A clean tapered trouser for warm-ups, travel and recovery days.", details:["Midweight loopback","Tapered ankle","Three pockets","Internal drawcord"] },
  { slug:"field-training-trouser", name:"Field Training Trouser", category:"Trousers", price:11490, sizes:["S","M","L","XL"], activity:"Conditioning", fit:"Slim", feature:"Water resistant", image:"https://images.unsplash.com/photo-1506629082955-511b1aa562c8?auto=format&fit=crop&w=1000&q=85", description:"Technical woven trouser with articulated knees and weather resistance.", details:["Water-resistant finish","Articulated knee","Ankle zip","Secure side pockets"] },
  { slug:"heatlock-sauna-suit", name:"Heatlock Sauna Suit", category:"Sauna", price:16990, badge:"Heat training", sizes:["M","L","XL","XXL"], activity:"Heat training", fit:"Regular", feature:"Heat retaining", image:"https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?auto=format&fit=crop&w=1000&q=85", description:"A lightweight heat-retaining shell for supervised, time-limited conditioning.", details:["Elasticated openings","Full front zip","Reflective detail","Not a fat-loss product"] },
  { slug:"heatlock-sauna-short", name:"Heatlock Sauna Short", category:"Sauna", price:8990, sizes:["M","L","XL"], activity:"Heat training", fit:"Regular", feature:"Heat retaining", image:"https://images.unsplash.com/photo-1571019614242-c5c5dee9f50b?auto=format&fit=crop&w=1000&q=85", description:"Heat-retaining training short for controlled sessions and easy layering.", details:["Elasticated waist","Two side pockets","Lightweight sealed shell","Hydrate before and after use"] },
  { slug:"whey-core", name:"Whey Core / Chocolate", category:"Supplements", price:12990, badge:"24g protein", sizes:["1kg","2kg"], activity:"Recovery", fit:"Chocolate", feature:"Protein", image:"https://images.unsplash.com/photo-1593095948071-474c5cc2989d?auto=format&fit=crop&w=1000&q=85", description:"Demo whey protein listing designed around transparent label reading.", details:["24g protein per demo serving","Nutrition label required before sale","Allergen disclosure required","Prototype product—not for purchase"] },
  { slug:"daily-creatine", name:"Daily Creatine / Unflavoured", category:"Supplements", price:7490, badge:"Pure mono", sizes:["300g","500g"], activity:"Performance", fit:"Unflavoured", feature:"Creatine", image:"https://images.unsplash.com/photo-1579722821273-0f6c1f354f0c?auto=format&fit=crop&w=1000&q=85", description:"Demo creatine monohydrate listing with no exaggerated performance claims.", details:["Single-ingredient concept","Batch testing required before sale","Usage must follow approved label","Prototype product—not for purchase"] },
  { slug:"feral-shaker", name:"FERAL Steel Shaker", category:"Supplements", price:4490, sizes:["750ml"], activity:"Everyday", fit:"Steel", feature:"Accessory", image:"https://images.unsplash.com/photo-1605296867304-46d5465a13f1?auto=format&fit=crop&w=1000&q=85", description:"Double-wall steel shaker with a clean threaded cap.", details:["750ml capacity","BPA-free lid","Hand wash recommended","Leak-resistant seal"] },
  { slug:"lifting-straps", name:"Heavy Pull Lifting Straps", category:"Supplements", price:2990, sizes:["One size"], activity:"Lifting", fit:"One size", feature:"Accessory", image:"https://images.unsplash.com/photo-1586401100295-7a8096fd231a?auto=format&fit=crop&w=1000&q=85", description:"Cotton lifting straps for controlled heavy pulling sessions.", details:["Reinforced stitching","Padded wrist","Sold as a pair","One size"] },
];

export const formatPrice = (value:number) => new Intl.NumberFormat("en-PK", { style:"currency", currency:"PKR", maximumFractionDigits:0 }).format(value);
