export type NavGroup={title:string;items:{label:string;slug:string}[]};
export type CommerceSection={slug:string;label:string;tagline:string;hero:string;groups:NavGroup[]};
export const commerceSections:CommerceSection[]=[
 {slug:"sale",label:"Sale",tagline:"End-of-line performance pieces. Same standard, sharper price.",hero:"https://images.unsplash.com/photo-1581009146145-b5ef050c2e1e?auto=format&fit=crop&w=1800&q=85",groups:[{title:"Shop sale",items:[{label:"All sale",slug:"all-sale"},{label:"Men's sale",slug:"mens-sale"},{label:"Women's sale",slug:"womens-sale"},{label:"Last sizes",slug:"last-sizes"}]}]},
 {slug:"men",label:"Men",tagline:"Performance layers engineered for lifting, conditioning and recovery.",hero:"https://images.unsplash.com/photo-1526506118085-60ce8714f8c5?auto=format&fit=crop&w=1800&q=85",groups:[{title:"Trending",items:[{label:"New arrivals",slug:"men-new-arrivals"},{label:"Best sellers",slug:"men-best-sellers"},{label:"Camo",slug:"men-camo"},{label:"Cozy season",slug:"men-cozy"},{label:"Oversized",slug:"men-oversized"},{label:"Compression",slug:"men-compression"}]},{title:"Products",items:[{label:"All products",slug:"men-all"},{label:"T-shirts & tops",slug:"men-tops"},{label:"Tanks",slug:"men-tanks"},{label:"Stringers",slug:"men-stringers"},{label:"Shorts",slug:"men-shorts"},{label:"Trousers",slug:"men-trousers"},{label:"Joggers",slug:"men-joggers"},{label:"Base layers",slug:"men-base-layers"},{label:"Underwear",slug:"men-underwear"},{label:"Jackets",slug:"men-jackets"},{label:"Hoodies",slug:"men-hoodies"}]},{title:"Collections",items:[{label:"Founder picks",slug:"men-founder-picks"},{label:"Dri-fit",slug:"men-dri-fit"},{label:"Polo shirts",slug:"men-polos"},{label:"Compression shirts",slug:"men-compression-shirts"},{label:"Oversized tees",slug:"men-oversized-tees"}]}]},
 {slug:"women",label:"Women",tagline:"Technical training fits with considered coverage, support and movement.",hero:"https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1800&q=85",groups:[{title:"Trending",items:[{label:"New drops",slug:"women-new-drops"},{label:"Camo",slug:"women-camo"},{label:"Compression",slug:"women-compression"},{label:"Oversized",slug:"women-oversized"},{label:"Seamless",slug:"women-seamless"}]},{title:"Products",items:[{label:"All products",slug:"women-all"},{label:"T-shirts & tops",slug:"women-tops"},{label:"Sports bras",slug:"women-sports-bras"},{label:"Tanks",slug:"women-tanks"},{label:"Crop tops",slug:"women-crop-tops"},{label:"Leggings",slug:"women-leggings"},{label:"Shorts",slug:"women-shorts"},{label:"Joggers",slug:"women-joggers"},{label:"Underwear",slug:"women-underwear"},{label:"Jackets & hoodies",slug:"women-jackets-hoodies"}]},{title:"Collections",items:[{label:"Feral Motion",slug:"women-feral-motion"},{label:"Core drop",slug:"women-core-drop"},{label:"Modest collection",slug:"women-modest"}]}]},
 {slug:"kids",label:"Kids",tagline:"Durable movement essentials for younger athletes.",hero:"https://images.unsplash.com/photo-1519315901367-f34ff9154487?auto=format&fit=crop&w=1800&q=85",groups:[{title:"Shop kids",items:[{label:"All products",slug:"kids-all"},{label:"Boys",slug:"kids-boys"},{label:"Girls",slug:"kids-girls"}]}]},
 {slug:"accessories",label:"Accessories",tagline:"The finishing equipment for training, travel and everyday carry.",hero:"https://images.unsplash.com/photo-1599058917212-d750089bc07e?auto=format&fit=crop&w=1800&q=85",groups:[{title:"Accessories",items:[{label:"All products",slug:"accessories-all"},{label:"New arrivals",slug:"accessories-new"},{label:"Slides",slug:"accessories-slides"},{label:"Bags",slug:"accessories-bags"},{label:"Caps",slug:"accessories-caps"},{label:"Gloves",slug:"accessories-gloves"},{label:"Socks",slug:"accessories-socks"},{label:"Shakers",slug:"accessories-shakers"},{label:"Lifting straps",slug:"accessories-straps"}]}]},
 {slug:"nutrition-store",label:"Nutrition",tagline:"Focused formulas and practical guidance without exaggerated claims.",hero:"https://images.unsplash.com/photo-1593095948071-474c5cc2989d?auto=format&fit=crop&w=1800&q=85",groups:[{title:"Shop nutrition",items:[{label:"All products",slug:"nutrition-all"},{label:"Clean protein",slug:"nutrition-clean-protein"},{label:"Protein",slug:"nutrition-protein"},{label:"Pre-workout",slug:"nutrition-pre-workout"},{label:"Multivitamins",slug:"nutrition-multivitamins"},{label:"Mass gainers",slug:"nutrition-mass-gainers"},{label:"Creatine",slug:"nutrition-creatine"}]},{title:"Learn",items:[{label:"Nutrition guidance",slug:"nutrition-guidance"},{label:"Protein basics",slug:"protein-basics"},{label:"Recovery",slug:"nutrition-recovery"}]}]},
 {slug:"b2b",label:"B2B",tagline:"Teamwear, gym partnerships and volume supply for performance businesses.",hero:"https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1800&q=85",groups:[{title:"Partnerships",items:[{label:"Gym wholesale",slug:"b2b-gym-wholesale"},{label:"Teamwear",slug:"b2b-teamwear"},{label:"Corporate wellness",slug:"b2b-corporate"},{label:"Request a quote",slug:"b2b-quote"}]}]},
];
export const sectionBySlug=(slug:string)=>commerceSections.find(section=>section.slug===slug);
export const subcategoryBySlug=(slug:string)=>commerceSections.flatMap(section=>section.groups.flatMap(group=>group.items.map(item=>({...item,section,group:group.title})))).find(item=>item.slug===slug);
